# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift, cannot, quickblox not support
# use_frameworks!

target 'TestJSQStatic' do
pod 'JSQMessagesViewController'
end

